services:
  namenode:
    build: 
      context: .
      dockerfile: Dockerfile.namenode
    restart: always
    ports:
      - 9870:9870 # Web UI
      - 9000:9000 # HDFS
      - 8088:8088
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./hadoop_config:/opt/hadoop-3.2.1/etc/hadoop
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode1:
    build: 
      context: .
      dockerfile: Dockerfile.datanode
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
      - ./hadoop_config:/opt/hadoop-3.2.1/etc/hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode2:
    build: 
      context: .
      dockerfile: Dockerfile.datanode
    restart: always
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
      - ./hadoop_config:/opt/hadoop-3.2.1/etc/hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2: